export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS'
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const MOSTRAR_ERROR_PRODUCTO = 'MOSTRAR_ERROR_PRODUCTO'

export const OBTENER_DETALLE_PRODUCTO = 'OBTENER_DETALLE_PRODUCTO'
